name: CI/CD Pipeline - Desafio Final
on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build API
        run: docker-compose up --build -d

      - name: Run tests
        run: docker-compose run api python -m unittest discover
      
      - name: Down docker-compose
        run: docker-compose down

      - name: Deploy to Render with Webhook
        run: |
          curl -X POST "$URL_WEBHOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.URL_WEBHOOK }}
